# Use an official node image as the base image
FROM node:alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code to the working directory
COPY . .

# Expose port 3000 for the Vite development server
EXPOSE 3000

# Start the Vite development server
CMD ["npm", "run", "dev"]
